# Add each famous admiral's personal BIO (verbatim from the faction Combined Fleet
# Stats PDFs) to data/faction-*.json admirals[]. The PDF text rendered em-dashes as
# "--"; per house style (no em-dashes) those become " - ". 6 admirals have no PDF bio
# (Gaius Chau, Magellan, and all four Bioficers) and are skipped.
import json

BIOS = {
  ('ucm', '“Granite” Halsey'): "Head of the most powerful institution mankind has ever known, Supreme Admiral Jacob 'Granite' Halsey is famous for his steely, brisk, borderline-offensive, flare. His rank grants him a permanent seat on the High Council, but his record there is of extensive truancy, not that anyone dares raise that. A career-sailor, his career began as a teenage rating aboard the ageing grand battleship UCMS Virginia, which he would, thirty-two years later, captain. His remaining on the bridge to the last as the venerable ship was wrecked by Shaltari privateers earned him a promotion to commodore, along with facial scarring and a lifetime's hatred for the 'filthy rotten stinking echidnas'. After another two decade's service as the UCMF's most battlehardened, pre-Reconquest commander, he attained mastery of the entire UCMF.\n\nPreferring to lead from the front, Halsey was present in the opening hours of the Battle for Earth, where, for the ninth time in his career, he had his CIC destroyed around him. Forced to command from the Shield of Aurum's auxiliary CIC, he remained a pivotal force in that titanic engagement, personally scoring nineteen capital ship kills in the first forty-eight hours.\n\nHalsey is a fixture on whichever frontline is hottest, and although he's burst some more blood vessels on his pockmarked face, he's at the razor's edge of command.",
  ('ucm', 'Havelock'): "Famous for her ice-cold head and killer instinct, June Havelock, 39, is the youngest admiral in the UCMF. Credited with spearheading the assault on D-Day - Earth from her battleship Carpe Noctum, she scored the most crucial kill of the day: the Scourge super-dreadnought Darkheart. One of the leading admirals of Battlefleet Sol, she regularly deputises supreme command above Earth. Thus far, Grand Admiral Halsey's respect and patronage has not been misplaced.\n\nHavelock climbed far, quickly. At the outbreak of the Reconquest, she was a lowly Lieutenant Commander aboard the cruiser UCMS Regalia, and was deemed competent if unspectacular. While the fires of war have never yet taken her head, the crucible of combat has forged her. Forced to take command of the crippled Regalia on D+3 - Eden, Havelock successfully rammed the Scourge battleship Sorn's Nemesis, destroying her and emerging as the only officer commanding to survive a ramming action that year.\n\nToday, she is one of the most decorated officers in the fleet and one of a handful to have been present at over four D-Days. Although she commands from a carrier-type battleship, she is noteworthy for her gunnery skills, since she values skilled crew in that area in particular.",
  ('ucm', 'Weaver'): "Admiral Weaver is never a name that the UCMA want to hear is backing them up. No fewer than 6 times they have required ground forces to make a mass, emergency extraction from an AO. Many Commanders believe that Weaver is a destructive maniac, levelling precious cities instead of letting ground forces do their thing. To an extent, that's true.\n\nWhile Weaver delights in ridding worlds of Scourge occupation and reducing their fleets to molten slag, the destruction of historically important sites always pains them deeply. Weaver is an avid historian, especially of golden age architecture. Prior to their enlistment they were on track to finish their masters degree at one of the most prestigious universities on Aurum. However, during the build-up to the Reconquest they felt it was part of their duty to reclaim their heritage before the Scourge ruin it forever.\n\nNow they seek to excise the corruption that are the Scourge. Using their Perth's laser like a precision scalpel, they burn away Scourge strongholds, glassing the parasites and everything around them. Their Flagship, Nicolum's Wrath has been in service since the start of the reconquest and has an impressive kill count. Despite this it's remained relatively undamaged throughout all its engagements. Thanks to minimal crew attrition, the officers are keenly aware of the limits of the ship and routinely use what other crews would call \"aggressive evasive manoeuvres\" to line up the perfect shot.",
  ('ucm', 'Tobias Tayne'): "Commodore Tobias Tayne is one of the UCMF's rising stars. An aggressive admiral that has seen through many engagements in command of one of the original run of Warsaw Heavy Cruisers. He played a pivotal role in the defence of Ferrum from the Scourge's surprise attack; his Battlegroup protected half a continent from Scourge attack and ensured the safety of several important Ferrum Motors factories.\n\nDespite his valiant efforts, his original Warsaw, the Aurum Eyes was irreparably damaged and consigned to scrap. For his efforts he was given a promotion to Commodore and assigned a new ship. Retaining most of his original crew, they settled into this latest-gen cruiser, the Aurum Eyes II.\n\nHaving spent the battle over Ferrum pushing the Aurum Eyes to its absolute limit and beyond, Tayne and his crew know exactly what the class is capable of. Due to this, they're a lot more willing to push the ship to the point just before structural failure to ensure their Cobra Lasers have the enemy in their sights.",
  ('phr', 'Claudia Rhee'): "Claudia Rhee is a rarity amongst the PHR. Once a Siren, her tactical aptitude and control over countless Familiars gained her a place as a Medusa, one of the most elite members of the already elite Siren Corps. She earned her place in the captains chair when her ship was ambushed by Shaltari pirates. Their initial volley had struck right through the ship's CIC, killing many of the command crew and leaving vital systems unmanned. Acting immediately, Claudia networked her Familiars with the ships' systems, restored order and brought weapons to bear. Her quick thinking saved the lives of many that day and while the ship itself was unsalvageable, Claudia was approached with an offer that would one day see her commanding not only her own ship, but an entire fleet.\n\nAs the daughter of Octavia Rhee, there has been high expectations of her since the day she was born. Fortunately for her she has exceeded every single one of them. She was able to control multiple Familiars by the time her peers were only just able to operate a single Familiar. She aced every single combat proficiency test thrown at her and her field operation record is impeccable.\n\nThough despite all of this she still lives in her mother's shadow, made even darker by her recent sacrifice in the Shangri-La system. While Claudia is determined to make those responsible pay, the alliances made before the Battle of Earth make this a difficult prospect as of late. It is only a matter of time, however, before that all breaks down, countless simulations calculated by her Familiars have shown her that over and over again.",
  ('phr', 'Helena of Asgard'): "Helena of Asgard is one of the most aggressive ranking officers active in the Asgard System. Part of the force tasked with destroying as many UCM Strike Carriers as possible. Retreating groups learned to steer clear of her flagship's Heavy Quad Battery lest the entire group be obliterated.\n\nWhile the UCM believe Helena is part of the external PHR forces, the truth is that Helena is an Asgard native. During the PHR's initial dealings with the resistance forces on Asgard Prime a young Helena started a rapport with PHR naval personnel, listening to tales of sights she would never see staying put on her home planet. Resolved to go with the returning PHR forces she sneaked aboard an outbound PHR transport. To her new allies, however, her infiltration attempt was painfully obvious.\n\nAlthough among plenty of other Asgardians that had decided to join their PHR allies, Helena showed great enthusiasm and promise in fleet-based operations. Proving herself again and again, Helena returned to Asgard Prime shortly before the ambush on the UCM fleet.",
  ('phr', 'Director Javelin'): "Director Javelin is a man of few words, and seemingly fewer actions. Every fleet movement, every communication, always short and to the point. He is not a man to mince words or waste effort on the superfluous. The UCM believe that Javelin is more machine than man, that his cold calculating persona is a complete lack of humanity.\n\nThe truth is that Javelin is rather lacking in many of the extra augmentations PHR admirals get to further interface with their ships. Making him more human than his peers. His cold stoicism comes from his natural temperament when dealing with the unknown, and his caution comes from the knowledge his high-level clearance burdens him with.\n\nHe values PHR life incredibly highly and will defend them with singular efficiency, even going so far as to force the hand of his superiors to allow prototype self-repairing armour systems to be installed on-board his flagship. Thanks to the extra durability this provides his flagship, Javelin is able to plant his feet, so to speak, on critical locations.",
  ('scourge', 'Overlord of Flies'): "The ship known as the Lord of Flies was one of the Scourge Dreadnoughts assigned to the Earth home fleet. It was last seen escorting a small battlegroup of unknown ship types to Earth's outer marker before jumping to an unknown destination.\n\nDuring the bulk of the fighting however, it was front and centre of one of the Scourge home fleets. Despite managing to take out several important UCM ships as well as inflicting damage on both the Shield of Aurum and Carpe Noctum, most of its battlegroup was destroyed in return fire.\n\nFalling back after the Shield of Aurum, Carpe Noctum, and their respective battlegroups destroyed the Darkheart, the Lord of Flies took on a more defensive role. Clearly the Scourge were wounded by the loss of the Darkheart and adjusted their battle tactics accordingly. Approximately 8 hours after the destruction of the Darkheart, the Lord of Flies made a course change that took it over Geneva, where it rendezvoused with a small fleet of ships not yet known to the UCM.\n\nAdmiral Havelock ordered all of her remaining Lima frigates to pursue and maintain an active scan on the unknown vessels. The Lord of Flies managed to hinder efforts by having its fighters and bombers swarm and obscure the mystery ships, which were summarily left behind when it, along with the unknown ships made their foldspace jumps elsewhere.",
  ('scourge', 'Baba Yaga'): "Baba Yaga is one of the oldest Scourge vessels witnessed by the UCM. One of the original ships that assaulted Eden Prime, analysis of data brought back to the UCM by stealth recon ships prior to the reconquest show that Baba Yaga was still present high above Eden Prime.\n\nHigh resolution scans of its hull show extensive repairs of battle damage, though reports from the exodus state that Baba Yaga saw very little combat during the initial invasion. Admiralty believe that this battle damage was gained during the Scourge's subjugation of the reptilian race they parasitised before humanity, as the damage patterns do not match anything either humanity, or the Shaltari were able to inflict at the time.\n\nDuring the reconquest of Eden Prime, Baba Yaga and its battlegroup were responsible for sending over 20,000 sailors to their deaths, before falling back to points unknown. Sporadic sightings of Baba Yaga have been reported over various combat theatres. The ship always appears and inflicts a heavy death toll before disappearing again.\n\nUCM Admiralty have designated Baba Yaga as a priority target to be taken out with extreme prejudice.",
  ('scourge', 'Flayer'): "Flayer was one of the ships seen during the Scourge's attack on Ferrum, though was assumed destroyed as UCM reinforcements arrived from Niccolum. Commodore Tayne's Battlegroup Aluminia Grit was the group responsible for defending the planet from Flayer's Battlegroup. The two Battlegroups would clash on more than one occasion, with both inflicting heavy casualties on each other in each bout. It was assumed that Flayer was eliminated during the last charge of the Aurum Eyes.\n\nThat assumption was later proven wrong, as a second Flayer seemingly appeared over Aluminia. Though completely different ships of the same pattern, their battle tactics were near identical to the original Flayer above Ferrum. This ship however, made it from the combat zone intact and later would reappear over Wolfrum.\n\nOnce again, Commodore Tayne and Flayer would lock horns. Despite their best efforts, neither of them could put a killing blow on the other, though many ships would meet their ends as collateral damage from these bouts. By the end of the battle over Wolfrum, Flayer would be unaccounted for, this time assumed alive and operational.",
  ('scourge', 'Enslaver'): "The Raiju designated Enslaver is one of the most reviled Scourge warships encountered during the reconquest. This admiral is usually seen at the head of a formation designed to board and capture enemy ships. Leading a host of Hiruko's, Akuma's, and more recently, Ebisu class ships, this admiral seems to revel in the capture of helpless ships. It is clear the reasons behind this, the Scourge lack for fresh supplies of hosts and without a new conquest they must make do with the relatively slim pickings afforded by battles in the void. Each ship they capture only adds to the enemy faced by humanity, thousands of capable sailors become unwilling hosts to the vile parasite.\n\nFortunately for the UCM, Enslaver has been seen in scant few combat areas, most notably counter-attacks against UCM forces during the reconquest. Months go by between sightings, suggesting lengthy transfers of personnel between engagements. Due to Enslaver's proclivity for capturing vessels, fleet command has issued fleet wide instructions to destroy this ship with extreme prejudice.",
  ('shaltari', 'Quetzalcoatl'): "Prime Starchief Quetzalcoatl has been a bane of UCM and PHR forces for the entirety of the Reconquest. Far too often the forces of one of the branches of Humanity will be winning an engagement against the Scourge only for Quetzalcoatl to arrive with his fleet and engage the existing combatants. In short order Quetzalcoatl annihilates the Capital Ships in the area and will then quickly leave the engagement, handing the Scourge a crucial victory.\n\nHowever, the very next day, as the Scourge seem close to victory, he'll reappear and destroy any Scourge Capital ships before they're able to retaliate and again leaves the area, handing victory to whoever is facing them. Quetzalcoatl's interference as part of a tribe that has not formally made itself known to the UCM shows that there are yet more Shaltari tribes that seek to prolong the conflict between Humanity and the Scourge.\n\nNo attempts at communication have succeeded, and he has been given a threat level of the highest priority, however currently, no one from the UCM or PHR have managed even the most cursory of communications with them, only gleaning the name from Pungari mercenaries that have themselves, only heard of Quetzalcoatl in name and reputation.",
  ('shaltari', 'Mergen the Learned'): "Mergen the Learned claims to have been alive long enough to have borne witness to the Shaltari's exodus from Aaru. Whether or not this is true can be left up for debate, but what is known is that this alabaster elder is an incredible tactician. Proving pivotal in the recapture of Aaru, Mergen was able to recall the exact sites of dormant Shaltari teleportation nodes. With this ancient knowledge Mergen's flagship, The Heart of the Mountain, was able to deploy vanguard battalions to critical locations ahead of the main Shaltari host.\n\nIn the void battles above the planet, Mergens fleet was responsible for sending a fifth of what Scourge remained above Aaru to their demise. The only other Starchief to achieve a similar number of confirmed kills was Quetzalcoatl, unsurprising given their martial prowess.\n\nWith the void above Aaru all but captured, Mergen is able to turn his attention to restoring the buried teleportation network on Aaru. Once his work on Aaru is done, the reclamation of other Shaltari strongholds awaits his attention.",
  ('shaltari', 'Seth'): "Starchief Seth is part of a Shaltari Tribe that specializes in the use of Gravity weapons. The use of these esoteric Shaltari weapons is incredibly hard to plan against, it's easier to defend against a weapon that destroys you, but one that has you turning the wrong way and flying towards your own fleet is much more difficult.\n\nSeth exemplifies these battle tactics of his tribe, his gravity weapons are more powerful than usual, a potentially unique modification in the otherwise standardized Shaltari arsenal. His ship will go in and out of orbital levels without any effort, allowing him to stage ambushes where, with a few well-placed shots, leaves an enemy battle plan in tatters.\n\nHis Sapphire Battlecruiser is a dreaded sight for any Reconquest leader, as soon as he is spotted, they know their best laid plans are already laid to waste. As often with the Shaltari, communication is erratic, and Seth has been known to engage in quite active communication at times, seemingly acting friendly, right up till he can activate his gravity weapons.",
  ('shaltari', 'Twins of Aaru'): "The twins have been sighted working alongside various tribes. Which has led UCM intelligence to believe they are some type of mercenary within Shaltari culture. However, their modus operandi is the same every time. Arriving in a pair of Amber class cruisers they will work with other cruisers and, via methods unknown to the UCM at this time, will increase the maneuverability of those ships giving the Shaltari fleet an unexpected advantage.\n\nThey are never seen separated, and even if one is destroyed, the next time they engage in fleet combat they'll be back together as a pair of Ambers. Causing chaos and disrupting even the most carefully laid plans by the Reconquest forces.\n\nAny Communication with the Twins has seen them actively mocking and teasing any forces they are battling, seemingly enjoying the chaos they cause and the destruction with a relish that seems unnerving.",
  ('resistance', 'Nguen'): "Originally conscripted from one of the poorest locales on Kalium, Nguen has seen a meteoric rise through the ranks of the Kalium navy. He has proven himself time and time again for the Kabal, his first command would see him trade blows with the Shaltari in anti-piracy actions protecting valuable in-system shipping routes.\n\nSince his start as a Vent Cannon technician, Nguen has gained an intimate understanding of the technology and physics behind the devastating weapons. Preferring commands on ships equipped with the unstable weapons, he's reduced scores of ships to molten metal, very few of which were his own.\n\nThe defining point of his career was the destruction of a trio of scourge battlecruisers with his previous command, a Gladiator class Grand Cruiser. Suffering serious damage after the destruction of one and the crippling of another, a final volley of vent fire overloaded the ships reactor. Ordering the ship to fly at full thrust towards the third and the call to abandon ship, Nguen would soon watch the reactor consume both his ship and the enemy battlecruiser from the relative safety of his escape vessel.\n\nUpon his return to Kalium, Nguen and his surviving crew would be assigned to the nearly complete Grosses Messer, overseeing its final reactor adjustments and being tasked with a live fire shakedown cruise.",
  ('resistance', 'Hagen'): "The Flagship of the independent High Technician known as Hagen is believed to have once belonged to the Kalium Kabal. Though quite why they would relinquish a working Battlecruiser to independents is currently unknown to UCM intelligence. Any chance to communicate and question those in Hagen's fleet state that it was \"empty when we found it\" and that the ship is \"legitimate salvage\".\n\nRegardless of how these independents acquired this ship, they seem more than capable of using and maintaining it. Having taken part in the battles above Luna, the Fortune's Fancy scored Hagen and his fleet several Scourge kills. The Fortune's Fancy is suspected to be highly modified, capable of carrying its standard launch compliment, along with a pair of internally stored torpedoes. Observations by the UCMF Saccharine show that these torpedoes are launched in the crudest way possible. Simply being allowed to float outwards from the bulk lander bays and fired while free floating.",
  ('resistance', 'Typhoon Vasquez'): "Typhoon Vasquez is the Head Engineer of the Red Baron, a pre-war ship used as a test-bed for various ammunition types designed for then-current Artillery Cannons. Vasquez's Battlegroup contains a large number of industrial ships, including the Andar Errente, a pre-war Industrial Raft. Thanks to copious amounts of manufacturing ability, Vasquez is able to be very liberal with the application of the various bootleg munitions produced by his fleet.\n\nVasquez's combat capable ships were present at the Battle for Earth and managed to score several Scourge kills. The Red Baron spent most of the engagement firing on any and every cylinder it could find. Vasquez's battle tactics seemed to either be genius, drawing most of the Scourge return fire towards the Red Baron and its ablative armour, or the absolute lunacy of being on constant weapons-free.",
}

# faction file -> admirals
files = {}
total = 0
for (faction, name), bio in BIOS.items():
    bio = bio.replace('--', ' - ')  # PDF rendered em-dashes as "--"; house style has none
    fp = 'data/faction-%s.json' % faction
    d = files.get(fp) or json.load(open(fp, encoding='utf-8'))
    files[fp] = d
    hit = False
    for a in d.get('admirals', []):
        if a.get('name') == name:
            a['bio'] = bio
            hit = True
            total += 1
    if not hit:
        print('!! no admiral match:', faction, repr(name))

for fp, d in files.items():
    json.dump(d, open(fp, 'w', encoding='utf-8', newline=''), indent=1, ensure_ascii=False)
    print('wrote', fp)
print('TOTAL bios applied:', total)
