#!/usr/bin/env python3
"""Build the hover spots for published scenario maps.

    PYTHONUTF8=1 python scripts/build-scenario-hotspots.py

Reads data/scenario-hotspots/<id>.json (marked with scenario-hotspot-tool.py)
and writes scenarios/dropfleet/scenario-hotspots.js. Each spot becomes
[tip, x, y, r], where tip names what the stats tooltip shows: a dropsite row,
a Feature, the Large Object scenery rules, or a Civilian ship card. A ship
spot is kept only when the scenario names which ship it is.
"""
import glob, io, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'data', 'scenario-hotspots')
LIB = os.path.join(ROOT, 'scenarios', 'dropfleet', 'scenario-lib.js')
OUT = os.path.join(ROOT, 'scenarios', 'dropfleet', 'scenario-hotspots.js')

DS = {'ss': 0, 'ms': 1, 'ls': 2, 'sc': 3, 'mc': 4, 'lc': 5}
FEAT = {'out': 'Military Outpost', 'odg': 'Orbital Defence Gun', 'com': 'Comms Station', 'pow': 'Power Plant', 'han': 'Hangar'}
SHIPS = ['Terminus Harvester', 'Flenser', 'Provenance Ark', 'Tugboat', 'Hyperyacht', 'Resupply Hauler', 'Dredger']


def scenario_text():
    out = {}
    # scenario-legacy.js adds the converted 1st edition scenarios, each as add({id:...})
    for lib in (LIB, os.path.join(os.path.dirname(LIB), 'scenario-legacy.js')):
        src = io.open(lib, encoding='utf-8').read()
        for m in re.finditer(r"\{id:'([^']+)'(.*?)(?=\n\s*(?:add\()?\{id:'|\n\];|\n\s*SCENARIOS\.push)", src, re.S):
            out[m.group(1)] = m.group(2)
    return out


def main():
    texts = scenario_text()
    result, dropped = {}, []
    for path in sorted(glob.glob(os.path.join(DATA, '*.json'))):
        sid = os.path.basename(path)[:-5]
        if sid not in texts:
            sys.exit('no scenario %s in scenario-lib.js' % sid)
        spots = []
        for s in json.load(io.open(path, encoding='utf-8')):
            t = s['t']
            if t in DS:
                tip = 'ds:%d' % DS[t]
            elif t in FEAT:
                tip = 'feat:' + FEAT[t]
            elif t == 'lo':
                tip = 'scen:Large Object'
            elif t == 'ship':
                named = [k for k in SHIPS if k in texts[sid]]
                if len(named) != 1:
                    dropped.append(sid)
                    continue
                tip = 'ship:' + named[0]
            else:
                sys.exit('unknown type %s in %s' % (t, sid))
            spot = [tip, s['x'], s['y'], s['r']]
            # a spot on a Variant's map layer carries it: {"v": "1"} shown with it, {"hideV": "1"} hidden by it
            layer = {k: s[k] for k in ('v', 'hideV') if k in s}
            if layer:
                spot.append(layer)
            spots.append(spot)
        if spots:
            result[sid] = sorted(spots, key=lambda v: -v[3])   # big first, so small Features sit on top
    js = ('// Generated by scripts/build-scenario-hotspots.py from data/scenario-hotspots. Do not edit by hand.\n'
          'const SCN_HOTSPOTS=%s;\n' % json.dumps(result, separators=(',', ':')))
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(js)
    print('%d maps, %d spots -> %s' % (len(result), sum(map(len, result.values())), os.path.relpath(OUT, ROOT)))
    if dropped:
        print('ship spots left out (scenario does not name the ship): %s' % ', '.join(sorted(set(dropped))))


if __name__ == '__main__':
    main()
